[tape]
alphabet = [0, 1]
T.0 = [0, 1, 1, 1, 0]

[program]
START S0
# END [S2, S3]
END S2
S0 {
  IF T.0 == "1" THEN {
    GOTO S1 {
      T.0: ["0", MOV_R]
    }
  }
  ELSE {
    GOTO S1 {
      T.0: ["1", MOV_R]
    }
  }
}

S1 {
  GOTO S0 {
    T.0: [T.0, MOV_L]
  }
}

