[tape]
alphabet = [1, 2 ,3]
T.0 = [a, b, c, d, 1, 3, 3, 2]

[program]
# comment 1
START S0
# comment 2
S0 {
  IF T.0 == "1" THEN
    GOTO S1 {
      T.0: ["1", MOV_R]
    }
  ELSE
    GOTO S0 {
      T.0: [T.0, MOV_R]
    }
}

S1 {
  GOTO S0 {
    T.0: [T.0, MOV_L]
  }
}

