[tape]
alphabet = [0, 1, _]
T.0 = [0, 0, 0, 0, 1, _]

[program]
START S0
END [S1]
S0 {
  IF (T.0 == "1") THEN {
    GOTO S0 {
      T.0: ["0", MOV_R]
    }
  }
  ELIF (T.0 == "0") THEN {
    GOTO S0 {
      T.0: ["1", MOV_R]
    }
  }
  ELSE {
    GOTO S1 {
      T.0: [T.0, STAY]
    }
  }
}

S1 {}

